package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/images/blocks/grid/arrowSprite.png", "assets/images/blocks/grid/arrowSprite.png");
			type.set ("assets/images/blocks/grid/arrowSprite.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/directionalUp.png", "assets/images/blocks/grid/directionalUp.png");
			type.set ("assets/images/blocks/grid/directionalUp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/output.png", "assets/images/blocks/grid/output.png");
			type.set ("assets/images/blocks/grid/output.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/blueBlock.png", "assets/images/blocks/grid/blueBlock.png");
			type.set ("assets/images/blocks/grid/blueBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/pinkBlock.png", "assets/images/blocks/grid/pinkBlock.png");
			type.set ("assets/images/blocks/grid/pinkBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/input.png", "assets/images/blocks/grid/input.png");
			type.set ("assets/images/blocks/grid/input.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/cyanBlock.png", "assets/images/blocks/grid/cyanBlock.png");
			type.set ("assets/images/blocks/grid/cyanBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/grid/greenBlock.png", "assets/images/blocks/grid/greenBlock.png");
			type.set ("assets/images/blocks/grid/greenBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/customizable/blueBlock.png", "assets/images/blocks/customizable/blueBlock.png");
			type.set ("assets/images/blocks/customizable/blueBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/customizable/pinkBlock.png", "assets/images/blocks/customizable/pinkBlock.png");
			type.set ("assets/images/blocks/customizable/pinkBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/customizable/cyanBlock.png", "assets/images/blocks/customizable/cyanBlock.png");
			type.set ("assets/images/blocks/customizable/cyanBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/customizable/arrow2X.png", "assets/images/blocks/customizable/arrow2X.png");
			type.set ("assets/images/blocks/customizable/arrow2X.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/customizable/greenBlock.png", "assets/images/blocks/customizable/greenBlock.png");
			type.set ("assets/images/blocks/customizable/greenBlock.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/grouper.png", "assets/images/blocks/icons/grouper.png");
			type.set ("assets/images/blocks/icons/grouper.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/directionalUp.png", "assets/images/blocks/icons/directionalUp.png");
			type.set ("assets/images/blocks/icons/directionalUp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/duplicator.png", "assets/images/blocks/icons/duplicator.png");
			type.set ("assets/images/blocks/icons/duplicator.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/waiter.png", "assets/images/blocks/icons/waiter.png");
			type.set ("assets/images/blocks/icons/waiter.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/ifred.png", "assets/images/blocks/icons/ifred.png");
			type.set ("assets/images/blocks/icons/ifred.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/iterator.png", "assets/images/blocks/icons/iterator.png");
			type.set ("assets/images/blocks/icons/iterator.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/signal.png", "assets/images/blocks/icons/signal.png");
			type.set ("assets/images/blocks/icons/signal.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/blocks/icons/addblack.png", "assets/images/blocks/icons/addblack.png");
			type.set ("assets/images/blocks/icons/addblack.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/levelSelector/Levels.png", "assets/images/levelSelector/Levels.png");
			type.set ("assets/images/levelSelector/Levels.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/levelSelector/discreptionPanel.png", "assets/images/levelSelector/discreptionPanel.png");
			type.set ("assets/images/levelSelector/discreptionPanel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/levelSelector/levelIcon.png", "assets/images/levelSelector/levelIcon.png");
			type.set ("assets/images/levelSelector/levelIcon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/seq/sig.png", "assets/images/seq/sig.png");
			type.set ("assets/images/seq/sig.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/seq/bolt.png", "assets/images/seq/bolt.png");
			type.set ("assets/images/seq/bolt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/seq/seq.png", "assets/images/seq/seq.png");
			type.set ("assets/images/seq/seq.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/GUI/panels/Container.png", "assets/images/GUI/panels/Container.png");
			type.set ("assets/images/GUI/panels/Container.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/GUI/buttons/plus.png", "assets/images/GUI/buttons/plus.png");
			type.set ("assets/images/GUI/buttons/plus.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/GUI/buttons/minus.png", "assets/images/GUI/buttons/minus.png");
			type.set ("assets/images/GUI/buttons/minus.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/GUI/buttons/question.png", "assets/images/GUI/buttons/question.png");
			type.set ("assets/images/GUI/buttons/question.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/customArrow2.png", "assets/images/useless images/customArrow2.png");
			type.set ("assets/images/useless images/customArrow2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/inputold.png", "assets/images/useless images/inputold.png");
			type.set ("assets/images/useless images/inputold.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalUps.png", "assets/images/useless images/directionalUps.png");
			type.set ("assets/images/useless images/directionalUps.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directional3.png", "assets/images/useless images/directional3.png");
			type.set ("assets/images/useless images/directional3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/sig.png", "assets/images/useless images/sig.png");
			type.set ("assets/images/useless images/sig.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/MINUS.png", "assets/images/useless images/MINUS.png");
			type.set ("assets/images/useless images/MINUS.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Entypo_2d(0)_24.png", "assets/images/useless images/Entypo_2d(0)_24.png");
			type.set ("assets/images/useless images/Entypo_2d(0)_24.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifgreen2.png", "assets/images/useless images/ifgreen2.png");
			type.set ("assets/images/useless images/ifgreen2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalxUp.png", "assets/images/useless images/directionalxUp.png");
			type.set ("assets/images/useless images/directionalxUp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifblue2.png", "assets/images/useless images/ifblue2.png");
			type.set ("assets/images/useless images/ifblue2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/iterator2.png", "assets/images/useless images/iterator2.png");
			type.set ("assets/images/useless images/iterator2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/images-go-here.txt", "assets/images/useless images/images-go-here.txt");
			type.set ("assets/images/useless images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/useless images/directional.png", "assets/images/useless images/directional.png");
			type.set ("assets/images/useless images/directional.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalUpd.png", "assets/images/useless images/directionalUpd.png");
			type.set ("assets/images/useless images/directionalUpd.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionala.png", "assets/images/useless images/directionala.png");
			type.set ("assets/images/useless images/directionala.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/bolt.png", "assets/images/useless images/bolt.png");
			type.set ("assets/images/useless images/bolt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/seq2.png", "assets/images/useless images/seq2.png");
			type.set ("assets/images/useless images/seq2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Entypo_2191(0)_36.bmp", "assets/images/useless images/Entypo_2191(0)_36.bmp");
			type.set ("assets/images/useless images/Entypo_2191(0)_36.bmp", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/useless images/color.png", "assets/images/useless images/color.png");
			type.set ("assets/images/useless images/color.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/outputs.png", "assets/images/useless images/outputs.png");
			type.set ("assets/images/useless images/outputs.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Entypo_2191(0)_32.png", "assets/images/useless images/Entypo_2191(0)_32.png");
			type.set ("assets/images/useless images/Entypo_2191(0)_32.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/output.png", "assets/images/useless images/output.png");
			type.set ("assets/images/useless images/output.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/duplicato2.png", "assets/images/useless images/duplicato2.png");
			type.set ("assets/images/useless images/duplicato2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/discreptionPanel.png", "assets/images/useless images/discreptionPanel.png");
			type.set ("assets/images/useless images/discreptionPanel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/customArrow0.png", "assets/images/useless images/customArrow0.png");
			type.set ("assets/images/useless images/customArrow0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/duplicators.png", "assets/images/useless images/duplicators.png");
			type.set ("assets/images/useless images/duplicators.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directional2.png", "assets/images/useless images/directional2.png");
			type.set ("assets/images/useless images/directional2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/waiter2.png", "assets/images/useless images/waiter2.png");
			type.set ("assets/images/useless images/waiter2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/customArrow4.png", "assets/images/useless images/customArrow4.png");
			type.set ("assets/images/useless images/customArrow4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Entypo_e4ad(0)_42.png", "assets/images/useless images/Entypo_e4ad(0)_42.png");
			type.set ("assets/images/useless images/Entypo_e4ad(0)_42.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionaly.png", "assets/images/useless images/directionaly.png");
			type.set ("assets/images/useless images/directionaly.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalUpd (2).png", "assets/images/useless images/directionalUpd (2).png");
			type.set ("assets/images/useless images/directionalUpd (2).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/inputd.png", "assets/images/useless images/inputd.png");
			type.set ("assets/images/useless images/inputd.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalUpi.png", "assets/images/useless images/directionalUpi.png");
			type.set ("assets/images/useless images/directionalUpi.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/outputold.png", "assets/images/useless images/outputold.png");
			type.set ("assets/images/useless images/outputold.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifgreen.png", "assets/images/useless images/ifgreen.png");
			type.set ("assets/images/useless images/ifgreen.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/duplicator.png", "assets/images/useless images/duplicator.png");
			type.set ("assets/images/useless images/duplicator.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalLeft.png", "assets/images/useless images/directionalLeft.png");
			type.set ("assets/images/useless images/directionalLeft.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/input.png", "assets/images/useless images/input.png");
			type.set ("assets/images/useless images/input.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Balanced_scale_of_Justice.svg", "assets/images/useless images/Balanced_scale_of_Justice.svg");
			type.set ("assets/images/useless images/Balanced_scale_of_Justice.svg", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/useless images/signal2.png", "assets/images/useless images/signal2.png");
			type.set ("assets/images/useless images/signal2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalsUp.png", "assets/images/useless images/directionalsUp.png");
			type.set ("assets/images/useless images/directionalsUp.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directional - Copy.png", "assets/images/useless images/directional - Copy.png");
			type.set ("assets/images/useless images/directional - Copy.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/seq.png", "assets/images/useless images/seq.png");
			type.set ("assets/images/useless images/seq.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/PLUS.png", "assets/images/useless images/PLUS.png");
			type.set ("assets/images/useless images/PLUS.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/duplicatsor.png", "assets/images/useless images/duplicatsor.png");
			type.set ("assets/images/useless images/duplicatsor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directional5.png", "assets/images/useless images/directional5.png");
			type.set ("assets/images/useless images/directional5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifblue.png", "assets/images/useless images/ifblue.png");
			type.set ("assets/images/useless images/ifblue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalDown.png", "assets/images/useless images/directionalDown.png");
			type.set ("assets/images/useless images/directionalDown.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directional4.png", "assets/images/useless images/directional4.png");
			type.set ("assets/images/useless images/directional4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifred2.png", "assets/images/useless images/ifred2.png");
			type.set ("assets/images/useless images/ifred2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/customArrow1.png", "assets/images/useless images/customArrow1.png");
			type.set ("assets/images/useless images/customArrow1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/signal.png", "assets/images/useless images/signal.png");
			type.set ("assets/images/useless images/signal.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/customArrow3.png", "assets/images/useless images/customArrow3.png");
			type.set ("assets/images/useless images/customArrow3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/transparent_spacer.gif", "assets/images/useless images/transparent_spacer.gif");
			type.set ("assets/images/useless images/transparent_spacer.gif", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/addblack.png", "assets/images/useless images/addblack.png");
			type.set ("assets/images/useless images/addblack.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/Entypo_2b(1)_24.png", "assets/images/useless images/Entypo_2b(1)_24.png");
			type.set ("assets/images/useless images/Entypo_2b(1)_24.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/ifblack.png", "assets/images/useless images/ifblack.png");
			type.set ("assets/images/useless images/ifblack.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/duplicatosr.png", "assets/images/useless images/duplicatosr.png");
			type.set ("assets/images/useless images/duplicatosr.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/arrow.png", "assets/images/useless images/arrow.png");
			type.set ("assets/images/useless images/arrow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/groupesr.png", "assets/images/useless images/groupesr.png");
			type.set ("assets/images/useless images/groupesr.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/useless images/directionalRight.png", "assets/images/useless images/directionalRight.png");
			type.set ("assets/images/useless images/directionalRight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/fonts/font.png", "assets/fonts/font.png");
			type.set ("assets/fonts/font.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/fonts/font.fnt", "assets/fonts/font.fnt");
			type.set ("assets/fonts/font.fnt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/bolt.png", "assets/data/bolt.png");
			type.set ("assets/data/bolt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/queries.xml", "assets/data/queries.xml");
			type.set ("assets/data/queries.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/powerup.wav", "assets/sounds/powerup.wav");
			type.set ("assets/sounds/powerup.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/fonts/nokiafc22.ttf", "assets/fonts/nokiafc22.ttf");
			type.set ("assets/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/arial.ttf", "assets/fonts/arial.ttf");
			type.set ("assets/fonts/arial.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
